### ISSUE TITLE
Feature Request: Ability to move through histories

### ISSUE THREAD

**Issue by PhantomTech** [IngenuityWP/AntiVandal#2]
- Ability to click on an entry in page revisions or user contributions to show that revision
  - Clicking on user history entries pushes the currently viewed diff off of the queue, loads the clicked one into the queue, and displays it
  - Clicking on page revision entries does not modify the queue, it only loads the diff and updates the history lists
- Hotkeys to do these movements, example: U, J = user history newer, older; I, K = revision history newer, older
- When intentionally viewing a old revision of a page, an option to restore the viewed revision is added

**Comment by IngenuityWP** [comment]
Done. Will be added in the next update (hopefully in the next few days).
