### ISSUE TITLE
after reading entire queue, "loading more results" hangs

### ISSUE THREAD

**Issue by NovemLinguae** [IngenuityWP/AntiVandal#5]
Steps to reproduce:

* load user script
* hit -> arrow button until queue has no items in it

What happens?

* user script hangs on this window infinitely
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/79697282/220377241-42e767d7-b43d-41fe-a52b-c54174b672e4.png">

What should happen instead?

* user script should add additional items to queue

Misc

* tried opening a new window/instance of the user script and it populated some items. so the problem isn't a lack of items available

**Comment by IngenuityWP** [comment]
Fixed. Will be added in the next update (hopefully in the next few days).
